global_options:
  dart_mappable_builder:
    options:
      renameMethods:
        fromJson: fromJsonString
        toJson: toJsonString
        fromMap: fromJson
        toMap: toJson
      generateMethods:
        - encode
        - decode
        - stringify
        - equals

targets:
  $default:
    builders:
      drift_dev:
        options:
          databases:
            werewolf_narrator_db: lib/database/database.dart
